package dmk.aesop.sms

object AesopSampleData {

  val json = """
    curJobs: [{
        "Id": 55555,
        "TenantId": 555,
        "Start": "2013-01-10T07:35:00",
        "EndDate": "2013-01-25T00:00:00",
        "Items": [{
            "Id": 55,
            "Start": "2013-01-10T07:35:00",
            "Duration": "07:30:00",
            "End": "2013-01-10T15:05:00",
            "ShiftType": 1,
            "NonPayTime": "00:00:00",
            "Institution": {
                "Name": "Easton High School",
                "Street1": "723 Mecklenburg Avenue",
                "Street2": null,
                "Street3": null,
                "Street4": null,
                "City": "Easton",
                "State": "MD",
                "Zip": "21601    ",
                "Phone": "(555) 555-5555",
                "ShowLocationPhoneToSub": true
            },
            "BreakDuration": "00:01:00",
            "VacancyId": 55,
            "CanCancel": false
        }, {
            "Id": 55,
            "Start": "2013-01-25T07:35:00",
            "Duration": "07:30:00",
            "End": "2013-01-25T15:05:00",
            "ShiftType": 1,
            "NonPayTime": "00:00:00",
            "Institution": {
                "Name": "Easton High School",
                "Street1": "723 Mecklenburg Avenue",
                "Street2": null,
                "Street3": null,
                "Street4": null,
                "City": "Easton",
                "State": "MD",
                "Zip": "21601    ",
                "Phone": "(555) 555-5555",
                "ShowLocationPhoneToSub": true
            },
            "BreakDuration": "00:01:00",
            "VacancyId": 55,
            "CanCancel": false
        }],
        "WorkerFirstName": "nosuch",
        "WorkerLastName": "nosuch",
        "WorkerTitle": "10th Grade English",
        "WorkerReportLocation": "5555",
        "WorkerEmail": "nosuch@k12.md.us",
        "WorkerIsVacancy": false,
        "ShowWorkerEmailAddrToSub": true,
        "HasNotes": true,
        "HasAttachments": false,
        "CanCancel": false,
        "SubWouldBePunishedForCancellingJob": false,
        "AwaitingFeedback": false,
        "CanViewFeedback": true,
        "CanViewFeedbackRating": true,
        "FeedbackRatingFromSub": null,
        "FeedbackRatingFromWorker": 2
    }, {
        "Id": 55,
        "TenantId": 5555,
        "Start": "2013-03-07T07:35:00",
        "EndDate": "2013-04-18T00:00:00",
        "Items": [{
            "Id": 55,
            "Start": "2013-03-07T07:35:00",
            "Duration": "07:30:00",
            "End": "2013-03-07T15:05:00",
            "ShiftType": 1,
            "NonPayTime": "00:00:00",
            "Institution": {
                "Name": "Easton High School",
                "Street1": "723 Mecklenburg Avenue",
                "Street2": null,
                "Street3": null,
                "Street4": null,
                "City": "Easton",
                "State": "MD",
                "Zip": "21601    ",
                "Phone": "(555) 555-5555",
                "ShowLocationPhoneToSub": true
            },
            "BreakDuration": "00:01:00",
            "VacancyId": 55,
            "CanCancel": false
        }, {
            "Id": 55,
            "Start": "2013-03-08T07:35:00",
            "Duration": "07:30:00",
            "End": "2013-03-08T15:05:00",
            "ShiftType": 1,
            "NonPayTime": "00:00:00",
            "Institution": {
                "Name": "Easton High School",
                "Street1": "723 Mecklenburg Avenue",
                "Street2": null,
                "Street3": null,
                "Street4": null,
                "City": "Easton",
                "State": "MD",
                "Zip": "21601    ",
                "Phone": "(555) 555-5555",
                "ShowLocationPhoneToSub": true
            },
            "BreakDuration": "00:01:00",
            "VacancyId": 55,
            "CanCancel": false
        }, {
            "Id": 55,
            "Start": "2013-03-11T07:35:00",
            "Duration": "07:30:00",
            "End": "2013-03-11T15:05:00",
            "ShiftType": 1,
            "NonPayTime": "00:00:00",
            "Institution": {
                "Name": "Easton High School",
                "Street1": "723 Mecklenburg Avenue",
                "Street2": null,
                "Street3": null,
                "Street4": null,
                "City": "Easton",
                "State": "MD",
                "Zip": "21601    ",
                "Phone": "(555) 555-5555",
                "ShowLocationPhoneToSub": true
            },
            "BreakDuration": "00:01:00",
            "VacancyId": 55,
            "CanCancel": false
        }, {
            "Id": 55,
            "Start": "2013-03-12T07:35:00",
            "Duration": "07:30:00",
            "End": "2013-03-12T15:05:00",
            "ShiftType": 1,
            "NonPayTime": "00:00:00",
            "Institution": {
                "Name": "Easton High School",
                "Street1": "723 Mecklenburg Avenue",
                "Street2": null,
                "Street3": null,
                "Street4": null,
                "City": "Easton",
                "State": "MD",
                "Zip": "21601    ",
                "Phone": "(555) 555-5555",
                "ShowLocationPhoneToSub": true
            },
            "BreakDuration": "00:01:00",
            "VacancyId": 55,
            "CanCancel": false
        }, {
            "Id": 5555,
            "Start": "2013-03-13T07:35:00",
            "Duration": "07:30:00",
            "End": "2013-03-13T15:05:00",
            "ShiftType": 1,
            "NonPayTime": "00:00:00",
            "Institution": {
                "Name": "Easton High School",
                "Street1": "723 Mecklenburg Avenue",
                "Street2": null,
                "Street3": null,
                "Street4": null,
                "City": "Easton",
                "State": "MD",
                "Zip": "21601    ",
                "Phone": "(555) 555-5555",
                "ShowLocationPhoneToSub": true
            },
            "BreakDuration": "00:01:00",
            "VacancyId": 555,
            "CanCancel": false
        }, {
            "Id": 555,
            "Start": "2013-03-14T07:35:00",
            "Duration": "07:30:00",
            "End": "2013-03-14T15:05:00",
            "ShiftType": 1,
            "NonPayTime": "00:00:00",
            "Institution": {
                "Name": "Easton High School",
                "Street1": "723 Mecklenburg Avenue",
                "Street2": null,
                "Street3": null,
                "Street4": null,
                "City": "Easton",
                "State": "MD",
                "Zip": "21601    ",
                "Phone": "(555) 555-5555",
                "ShowLocationPhoneToSub": true
            },
            "BreakDuration": "00:01:00",
            "VacancyId": 55,
            "CanCancel": false
        }, {
            "Id": 5555,
            "Start": "2013-03-15T07:35:00",
            "Duration": "07:30:00",
            "End": "2013-03-15T15:05:00",
            "ShiftType": 1,
            "NonPayTime": "00:00:00",
            "Institution": {
                "Name": "Easton High School",
                "Street1": "723 Mecklenburg Avenue",
                "Street2": null,
                "Street3": null,
                "Street4": null,
                "City": "Easton",
                "State": "MD",
                "Zip": "21601    ",
                "Phone": "(555) 555-5555",
                "ShowLocationPhoneToSub": true
            },
            "BreakDuration": "00:01:00",
            "VacancyId": 55,
            "CanCancel": false
        }, {
            "Id": 55,
            "Start": "2013-03-18T07:35:00",
            "Duration": "07:30:00",
            "End": "2013-03-18T15:05:00",
            "ShiftType": 1,
            "NonPayTime": "00:00:00",
            "Institution": {
                "Name": "Easton High School",
                "Street1": "723 Mecklenburg Avenue",
                "Street2": null,
                "Street3": null,
                "Street4": null,
                "City": "Easton",
                "State": "MD",
                "Zip": "21601    ",
                "Phone": "(555) 555-5555",
                "ShowLocationPhoneToSub": true
            },
            "BreakDuration": "00:01:00",
            "VacancyId": 555,
            "CanCancel": false
        }, {
            "Id": 555,
            "Start": "2013-03-19T07:35:00",
            "Duration": "07:30:00",
            "End": "2013-03-19T15:05:00",
            "ShiftType": 1,
            "NonPayTime": "00:00:00",
            "Institution": {
                "Name": "Easton High School",
                "Street1": "723 Mecklenburg Avenue",
                "Street2": null,
                "Street3": null,
                "Street4": null,
                "City": "Easton",
                "State": "MD",
                "Zip": "21601    ",
                "Phone": "(555) 555-5555",
                "ShowLocationPhoneToSub": true
            },
            "BreakDuration": "00:01:00",
            "VacancyId": 55,
            "CanCancel": false
        }, {
            "Id": 555,
            "Start": "2013-03-20T07:35:00",
            "Duration": "07:30:00",
            "End": "2013-03-20T15:05:00",
            "ShiftType": 1,
            "NonPayTime": "00:00:00",
            "Institution": {
                "Name": "Easton High School",
                "Street1": "723 Mecklenburg Avenue",
                "Street2": null,
                "Street3": null,
                "Street4": null,
                "City": "Easton",
                "State": "MD",
                "Zip": "21601    ",
                "Phone": "(555) 555-5555",
                "ShowLocationPhoneToSub": true
            },
            "BreakDuration": "00:01:00",
            "VacancyId": 55,
            "CanCancel": false
        }, {
            "Id": 55,
            "Start": "2013-03-21T07:35:00",
            "Duration": "07:30:00",
            "End": "2013-03-21T15:05:00",
            "ShiftType": 1,
            "NonPayTime": "00:00:00",
            "Institution": {
                "Name": "Easton High School",
                "Street1": "723 Mecklenburg Avenue",
                "Street2": null,
                "Street3": null,
                "Street4": null,
                "City": "Easton",
                "State": "MD",
                "Zip": "21601    ",
                "Phone": "(555) 555-5555",
                "ShowLocationPhoneToSub": true
            },
            "BreakDuration": "00:01:00",
            "VacancyId": 55,
            "CanCancel": false
        }, {
            "Id": 555,
            "Start": "2013-03-22T07:35:00",
            "Duration": "07:30:00",
            "End": "2013-03-22T15:05:00",
            "ShiftType": 1,
            "NonPayTime": "00:00:00",
            "Institution": {
                "Name": "Easton High School",
                "Street1": "723 Mecklenburg Avenue",
                "Street2": null,
                "Street3": null,
                "Street4": null,
                "City": "Easton",
                "State": "MD",
                "Zip": "21601    ",
                "Phone": "(555) 555-5555",
                "ShowLocationPhoneToSub": true
            },
            "BreakDuration": "00:01:00",
            "VacancyId": 55,
            "CanCancel": false
        }, {
            "Id": 555,
            "Start": "2013-03-25T07:35:00",
            "Duration": "07:30:00",
            "End": "2013-03-25T15:05:00",
            "ShiftType": 1,
            "NonPayTime": "00:00:00",
            "Institution": {
                "Name": "Easton High School",
                "Street1": "723 Mecklenburg Avenue",
                "Street2": null,
                "Street3": null,
                "Street4": null,
                "City": "Easton",
                "State": "MD",
                "Zip": "21601    ",
                "Phone": "(555) 555-5555",
                "ShowLocationPhoneToSub": true
            },
            "BreakDuration": "00:01:00",
            "VacancyId": 555,
            "CanCancel": false
        }, {
            "Id": 5555,
            "Start": "2013-03-26T07:35:00",
            "Duration": "07:30:00",
            "End": "2013-03-26T15:05:00",
            "ShiftType": 1,
            "NonPayTime": "00:00:00",
            "Institution": {
                "Name": "Easton High School",
                "Street1": "723 Mecklenburg Avenue",
                "Street2": null,
                "Street3": null,
                "Street4": null,
                "City": "Easton",
                "State": "MD",
                "Zip": "21601    ",
                "Phone": "(555) 555-5555",
                "ShowLocationPhoneToSub": true
            },
            "BreakDuration": "00:01:00",
            "VacancyId": 555,
            "CanCancel": false
        }, {
            "Id": 55555,
            "Start": "2013-03-27T07:35:00",
            "Duration": "07:30:00",
            "End": "2013-03-27T15:05:00",
            "ShiftType": 1,
            "NonPayTime": "00:00:00",
            "Institution": {
                "Name": "Easton High School",
                "Street1": "723 Mecklenburg Avenue",
                "Street2": null,
                "Street3": null,
                "Street4": null,
                "City": "Easton",
                "State": "MD",
                "Zip": "21601    ",
                "Phone": "(555) 555-5555",
                "ShowLocationPhoneToSub": true
            },
            "BreakDuration": "00:01:00",
            "VacancyId": 55,
            "CanCancel": false
        }, {
            "Id": 55,
            "Start": "2013-04-03T07:35:00",
            "Duration": "07:30:00",
            "End": "2013-04-03T15:05:00",
            "ShiftType": 1,
            "NonPayTime": "00:00:00",
            "Institution": {
                "Name": "Easton High School",
                "Street1": "723 Mecklenburg Avenue",
                "Street2": null,
                "Street3": null,
                "Street4": null,
                "City": "Easton",
                "State": "MD",
                "Zip": "21601    ",
                "Phone": "(555) 555-5555",
                "ShowLocationPhoneToSub": true
            },
            "BreakDuration": "00:01:00",
            "VacancyId": 5555,
            "CanCancel": false
        }, {
            "Id": 55555,
            "Start": "2013-04-04T07:35:00",
            "Duration": "07:30:00",
            "End": "2013-04-04T15:05:00",
            "ShiftType": 1,
            "NonPayTime": "00:00:00",
            "Institution": {
                "Name": "Easton High School",
                "Street1": "723 Mecklenburg Avenue",
                "Street2": null,
                "Street3": null,
                "Street4": null,
                "City": "Easton",
                "State": "MD",
                "Zip": "21601    ",
                "Phone": "(555) 555-5555",
                "ShowLocationPhoneToSub": true
            },
            "BreakDuration": "00:01:00",
            "VacancyId": 55555,
            "CanCancel": false
        }, {
            "Id": 555555,
            "Start": "2013-04-05T07:35:00",
            "Duration": "07:30:00",
            "End": "2013-04-05T15:05:00",
            "ShiftType": 1,
            "NonPayTime": "00:00:00",
            "Institution": {
                "Name": "Easton High School",
                "Street1": "723 Mecklenburg Avenue",
                "Street2": null,
                "Street3": null,
                "Street4": null,
                "City": "Easton",
                "State": "MD",
                "Zip": "21601    ",
                "Phone": "(555) 555-5555",
                "ShowLocationPhoneToSub": true
            },
            "BreakDuration": "00:01:00",
            "VacancyId": 55555,
            "CanCancel": false
        }, {
            "Id": 555555,
            "Start": "2013-04-08T07:35:00",
            "Duration": "07:30:00",
            "End": "2013-04-08T15:05:00",
            "ShiftType": 1,
            "NonPayTime": "00:00:00",
            "Institution": {
                "Name": "Easton High School",
                "Street1": "723 Mecklenburg Avenue",
                "Street2": null,
                "Street3": null,
                "Street4": null,
                "City": "Easton",
                "State": "MD",
                "Zip": "21601    ",
                "Phone": "(555) 555-5555",
                "ShowLocationPhoneToSub": true
            },
            "BreakDuration": "00:01:00",
            "VacancyId": 55555,
            "CanCancel": false
        }, {
            "Id": 55555,
            "Start": "2013-04-09T07:35:00",
            "Duration": "07:30:00",
            "End": "2013-04-09T15:05:00",
            "ShiftType": 1,
            "NonPayTime": "00:00:00",
            "Institution": {
                "Name": "Easton High School",
                "Street1": "723 Mecklenburg Avenue",
                "Street2": null,
                "Street3": null,
                "Street4": null,
                "City": "Easton",
                "State": "MD",
                "Zip": "21601    ",
                "Phone": "(555) 555-5555",
                "ShowLocationPhoneToSub": true
            },
            "BreakDuration": "00:01:00",
            "VacancyId": 55555,
            "CanCancel": false
        }, {
            "Id": 55555,
            "Start": "2013-04-10T07:35:00",
            "Duration": "07:30:00",
            "End": "2013-04-10T15:05:00",
            "ShiftType": 1,
            "NonPayTime": "00:00:00",
            "Institution": {
                "Name": "Easton High School",
                "Street1": "723 Mecklenburg Avenue",
                "Street2": null,
                "Street3": null,
                "Street4": null,
                "City": "Easton",
                "State": "MD",
                "Zip": "21601    ",
                "Phone": "(555) 555-5555",
                "ShowLocationPhoneToSub": true
            },
            "BreakDuration": "00:01:00",
            "VacancyId": 55555,
            "CanCancel": false
        }, {
            "Id": 55555,
            "Start": "2013-04-11T07:35:00",
            "Duration": "07:30:00",
            "End": "2013-04-11T15:05:00",
            "ShiftType": 1,
            "NonPayTime": "00:00:00",
            "Institution": {
                "Name": "Easton High School",
                "Street1": "723 Mecklenburg Avenue",
                "Street2": null,
                "Street3": null,
                "Street4": null,
                "City": "Easton",
                "State": "MD",
                "Zip": "21601    ",
                "Phone": "(555) 555-5555",
                "ShowLocationPhoneToSub": true
            },
            "BreakDuration": "00:01:00",
            "VacancyId": 555555,
            "CanCancel": false
        }, {
            "Id": 5555,
            "Start": "2013-04-12T07:35:00",
            "Duration": "07:30:00",
            "End": "2013-04-12T15:05:00",
            "ShiftType": 1,
            "NonPayTime": "00:00:00",
            "Institution": {
                "Name": "Easton High School",
                "Street1": "723 Mecklenburg Avenue",
                "Street2": null,
                "Street3": null,
                "Street4": null,
                "City": "Easton",
                "State": "MD",
                "Zip": "21601    ",
                "Phone": "(555) 555-5555",
                "ShowLocationPhoneToSub": true
            },
            "BreakDuration": "00:01:00",
            "VacancyId": 55555,
            "CanCancel": false
        }, {
            "Id": 55555,
            "Start": "2013-04-15T07:35:00",
            "Duration": "07:30:00",
            "End": "2013-04-15T15:05:00",
            "ShiftType": 1,
            "NonPayTime": "00:00:00",
            "Institution": {
                "Name": "Easton High School",
                "Street1": "723 Mecklenburg Avenue",
                "Street2": null,
                "Street3": null,
                "Street4": null,
                "City": "Easton",
                "State": "MD",
                "Zip": "21601    ",
                "Phone": "(555) 555-5555",
                "ShowLocationPhoneToSub": true
            },
            "BreakDuration": "00:01:00",
            "VacancyId": 55555,
            "CanCancel": false
        }, {
            "Id": 5555,
            "Start": "2013-04-16T07:35:00",
            "Duration": "07:30:00",
            "End": "2013-04-16T15:05:00",
            "ShiftType": 1,
            "NonPayTime": "00:00:00",
            "Institution": {
                "Name": "Easton High School",
                "Street1": "723 Mecklenburg Avenue",
                "Street2": null,
                "Street3": null,
                "Street4": null,
                "City": "Easton",
                "State": "MD",
                "Zip": "21601    ",
                "Phone": "(555) 555-5555",
                "ShowLocationPhoneToSub": true
            },
            "BreakDuration": "00:01:00",
            "VacancyId": 55555,
            "CanCancel": false
        }, {
            "Id": 555555,
            "Start": "2013-04-17T07:35:00",
            "Duration": "07:30:00",
            "End": "2013-04-17T15:05:00",
            "ShiftType": 1,
            "NonPayTime": "00:00:00",
            "Institution": {
                "Name": "Easton High School",
                "Street1": "723 Mecklenburg Avenue",
                "Street2": null,
                "Street3": null,
                "Street4": null,
                "City": "Easton",
                "State": "MD",
                "Zip": "21601    ",
                "Phone": "(555) 555-5555",
                "ShowLocationPhoneToSub": true
            },
            "BreakDuration": "00:01:00",
            "VacancyId": 55555,
            "CanCancel": false
        }, {
            "Id": 137490081,
            "Start": "2014-04-18T07:35:00",
            "Duration": "07:30:00",
            "End": "2014-04-18T15:05:00",
            "ShiftType": 1,
            "NonPayTime": "00:00:00",
            "Institution": {
                "Name": "Easton High School",
                "Street1": "723 Mecklenburg Avenue",
                "Street2": null,
                "Street3": null,
                "Street4": null,
                "City": "Easton",
                "State": "MD",
                "Zip": "21601    ",
                "Phone": "(555) 555-5555",
                "ShowLocationPhoneToSub": true
            },
            "BreakDuration": "00:01:00",
            "VacancyId": 5555,
            "CanCancel": false
        }],
        "WorkerFirstName": "nosuchfirst",
        "WorkerLastName": "nosuchlast",
        "WorkerTitle": "10th Grade English",
        "WorkerReportLocation": "111",
        "WorkerEmail": "nosuchfirst@k12.md.us",
        "WorkerIsVacancy": false,
        "ShowWorkerEmailAddrToSub": true,
        "HasNotes": false,
        "HasAttachments": false,
        "CanCancel": false,
        "SubWouldBePunishedForCancellingJob": false,
        "AwaitingFeedback": false,
        "CanViewFeedback": true,
        "CanViewFeedbackRating": true,
        "FeedbackRatingFromSub": null,
        "FeedbackRatingFromWorker": null
    }, {
        "Id": 555555,
        "TenantId": 555,
        "Start": "2016-10-23T07:30:00",
        "EndDate": "2016-11-06T00:00:00",
        "Items": [{
            "Id": 55555,
            "Start": "2016-10-23T07:30:00",
            "Duration": "07:30:00",
            "End": "2016-10-23T15:00:00",
            "ShiftType": 1,
            "NonPayTime": "00:00:00",
            "Institution": {
                "Name": "St. Michaels Middle/High",
                "Street1": "200 Seymour Avenue",
                "Street2": null,
                "Street3": null,
                "Street4": null,
                "City": "St. Michaels",
                "State": "MD",
                "Zip": "21663    ",
                "Phone": "555 555-5555",
                "ShowLocationPhoneToSub": true
            },
            "BreakDuration": "00:01:00",
            "VacancyId": 55555,
            "CanCancel": false
        }, {
            "Id": 555555,
            "Start": "2016-10-24T07:30:00",
            "Duration": "07:30:00",
            "End": "2016-10-24T15:00:00",
            "ShiftType": 1,
            "NonPayTime": "00:00:00",
            "Institution": {
                "Name": "St. Michaels Middle/High",
                "Street1": "200 Seymour Avenue",
                "Street2": null,
                "Street3": null,
                "Street4": null,
                "City": "St. Michaels",
                "State": "MD",
                "Zip": "21663    ",
                "Phone": "555 555-5555",
                "ShowLocationPhoneToSub": true
            },
            "BreakDuration": "00:01:00",
            "VacancyId": 55555,
            "CanCancel": false
        }, {
            "Id": 555555,
            "Start": "2016-10-25T07:30:00",
            "Duration": "07:30:00",
            "End": "2016-10-25T15:00:00",
            "ShiftType": 1,
            "NonPayTime": "00:00:00",
            "Institution": {
                "Name": "St. Michaels Middle/High",
                "Street1": "200 Seymour Avenue",
                "Street2": null,
                "Street3": null,
                "Street4": null,
                "City": "St. Michaels",
                "State": "MD",
                "Zip": "21663    ",
                "Phone": "555 555-5555",
                "ShowLocationPhoneToSub": true
            },
            "BreakDuration": "00:01:00",
            "VacancyId": 5555,
            "CanCancel": false
        }, {
            "Id": 55555,
            "Start": "2016-10-26T07:30:00",
            "Duration": "07:30:00",
            "End": "2016-10-26T15:00:00",
            "ShiftType": 1,
            "NonPayTime": "00:00:00",
            "Institution": {
                "Name": "St. Michaels Middle/High",
                "Street1": "200 Seymour Avenue",
                "Street2": null,
                "Street3": null,
                "Street4": null,
                "City": "St. Michaels",
                "State": "MD",
                "Zip": "21663    ",
                "Phone": "555 555-5555",
                "ShowLocationPhoneToSub": true
            },
            "BreakDuration": "00:01:00",
            "VacancyId": 5555,
            "CanCancel": false
        }, {
            "Id": 555555,
            "Start": "2016-11-01T07:30:00",
            "Duration": "07:30:00",
            "End": "2016-11-01T15:00:00",
            "ShiftType": 1,
            "NonPayTime": "00:00:00",
            "Institution": {
                "Name": "St. Michaels Middle/High",
                "Street1": "200 Seymour Avenue",
                "Street2": null,
                "Street3": null,
                "Street4": null,
                "City": "St. Michaels",
                "State": "MD",
                "Zip": "21663    ",
                "Phone": "555 555-5555",
                "ShowLocationPhoneToSub": true
            },
            "BreakDuration": "00:01:00",
            "VacancyId": 93895370,
            "CanCancel": false
        }, {
            "Id": 55555,
            "Start": "2016-11-02T07:30:00",
            "Duration": "07:30:00",
            "End": "2016-11-02T15:00:00",
            "ShiftType": 1,
            "NonPayTime": "00:00:00",
            "Institution": {
                "Name": "St. Michaels Middle/High",
                "Street1": "200 Seymour Avenue",
                "Street2": null,
                "Street3": null,
                "Street4": null,
                "City": "St. Michaels",
                "State": "MD",
                "Zip": "21663    ",
                "Phone": "555 555-5555",
                "ShowLocationPhoneToSub": true
            },
            "BreakDuration": "00:01:00",
            "VacancyId": 4444444,
            "CanCancel": false
        }, {
            "Id": 4444444,
            "Start": "2016-11-05T07:30:00",
            "Duration": "07:30:00",
            "End": "2016-11-05T15:00:00",
            "ShiftType": 1,
            "NonPayTime": "00:00:00",
            "Institution": {
                "Name": "St. Michaels Middle/High",
                "Street1": "200 Seymour Avenue",
                "Street2": null,
                "Street3": null,
                "Street4": null,
                "City": "St. Michaels",
                "State": "MD",
                "Zip": "21663    ",
                "Phone": "(555) 555-5555",
                "ShowLocationPhoneToSub": true
            },
            "BreakDuration": "00:01:00",
            "VacancyId": 5555555,
            "CanCancel": false
        }, {
            "Id": 55555,
            "Start": "2016-11-06T07:30:00",
            "Duration": "07:30:00",
            "End": "2016-11-06T15:00:00",
            "ShiftType": 1,
            "NonPayTime": "00:00:00",
            "Institution": {
                "Name": "St. Michaels Middle/High",
                "Street1": "200 Seymour Avenue",
                "Street2": null,
                "Street3": null,
                "Street4": null,
                "City": "St. Michaels",
                "State": "MD",
                "Zip": "21663    ",
                "Phone": "(5555) 5555-5555",
                "ShowLocationPhoneToSub": true
            },
            "BreakDuration": "00:01:00",
            "VacancyId": 5555555,
            "CanCancel": false
        }],
        "WorkerFirstName": "nosuch",
        "WorkerLastName": "nosuchlast",
        "WorkerTitle": "Physical Science/Environmental",
        "WorkerReportLocation": "Main Office",
        "WorkerEmail": "nosuch@gmail.com",
        "WorkerIsVacancy": false,
        "ShowWorkerEmailAddrToSub": true,
        "HasNotes": true,
        "HasAttachments": false,
        "CanCancel": false,
        "SubWouldBePunishedForCancellingJob": false,
        "AwaitingFeedback": false,
        "CanViewFeedback": true,
        "CanViewFeedbackRating": true,
        "FeedbackRatingFromSub": 4,
        "FeedbackRatingFromWorker": null
    }, {
        "Id": 555555,
        "TenantId": 45555,
        "Start": "2015-11-12T07:30:00",
        "EndDate": "2015-11-12T00:00:00",
        "Items": [{
            "Id": 5555555,
            "Start": "2015-11-12T07:30:00",
            "Duration": "07:30:00",
            "End": "2015-11-12T15:00:00",
            "ShiftType": 1,
            "NonPayTime": "00:00:00",
            "Institution": {
                "Name": "St. Michaels Middle/High",
                "Street1": "200 Seymour Avenue",
                "Street2": null,
                "Street3": null,
                "Street4": null,
                "City": "St. Michaels",
                "State": "MD",
                "Zip": "21663    ",
                "Phone": "(555) 555-5555",
                "ShowLocationPhoneToSub": true
            },
            "BreakDuration": "00:01:00",
            "VacancyId": 5555555,
            "CanCancel": false
        }],
        "WorkerFirstName": "nosuchfirst1",
        "WorkerLastName": "nosuchlast1",
        "WorkerTitle": "English",
        "WorkerReportLocation": "Main Office",
        "WorkerEmail": "nosuch@tcps.k12.md.us",
        "WorkerIsVacancy": false,
        "ShowWorkerEmailAddrToSub": true,
        "HasNotes": false,
        "HasAttachments": false,
        "CanCancel": false,
        "SubWouldBePunishedForCancellingJob": false,
        "AwaitingFeedback": false,
        "CanViewFeedback": true,
        "CanViewFeedbackRating": true,
        "FeedbackRatingFromSub": 5,
        "FeedbackRatingFromWorker": null
    }, {
        "Id": 555555,
        "TenantId": 555,
        "Start": "2015-11-13T07:35:00",
        "EndDate": "2015-11-13T00:00:00",
        "Items": [{
            "Id": 5555,
            "Start": "2015-11-13T07:35:00",
            "Duration": "07:30:00",
            "End": "2015-11-13T15:05:00",
            "ShiftType": 1,
            "NonPayTime": "00:00:00",
            "Institution": {
                "Name": "Easton High School",
                "Street1": "723 Mecklenburg Avenue",
                "Street2": null,
                "Street3": null,
                "Street4": null,
                "City": "Easton",
                "State": "MD",
                "Zip": "21601    ",
                "Phone": "(555) 555-5555",
                "ShowLocationPhoneToSub": true
            },
            "BreakDuration": "00:01:00",
            "VacancyId": 555555,
            "CanCancel": false
        }],
        "WorkerFirstName": "nosuch1st",
        "WorkerLastName": "nosuchlst",
        "WorkerTitle": "10th Grade English",
        "WorkerReportLocation": "Main Office",
        "WorkerEmail": "nosuchemailk12.md.us",
        "WorkerIsVacancy": false,
        "ShowWorkerEmailAddrToSub": true,
        "HasNotes": true,
        "HasAttachments": false,
        "CanCancel": false,
        "SubWouldBePunishedForCancellingJob": false,
        "AwaitingFeedback": false,
        "CanViewFeedback": true,
        "CanViewFeedbackRating": true,
        "FeedbackRatingFromSub": 5,
        "FeedbackRatingFromWorker": 5
    }, {
        "Id": 555555,
        "TenantId": 5555,
        "Start": "2015-11-19T08:30:00",
        "EndDate": "2015-11-19T00:00:00",
        "Items": [{
            "Id": 555555,
            "Start": "2015-11-19T08:30:00",
            "Duration": "07:30:00",
            "End": "2015-11-19T16:00:00",
            "ShiftType": 1,
            "NonPayTime": "00:00:00",
            "Institution": {
                "Name": "Easton Elementary-Dobson",
                "Street1": "305 Glenwood Avenue",
                "Street2": null,
                "Street3": null,
                "Street4": null,
                "City": "Easton",
                "State": "MD",
                "Zip": "21601    ",
                "Phone": "(555) 555-5555",
                "ShowLocationPhoneToSub": true
            },
            "BreakDuration": "00:01:00",
            "VacancyId": 5555555,
            "CanCancel": false
        }],
        "WorkerFirstName": "nosuchfirst",
        "WorkerLastName": "nosuchlast",
        "WorkerTitle": "Special Education",
        "WorkerReportLocation": "Main Office",
        "WorkerEmail": null,
        "WorkerIsVacancy": false,
        "ShowWorkerEmailAddrToSub": true,
        "HasNotes": false,
        "HasAttachments": false,
        "CanCancel": false,
        "SubWouldBePunishedForCancellingJob": false,
        "AwaitingFeedback": true,
        "CanViewFeedback": true,
        "CanViewFeedbackRating": true,
        "FeedbackRatingFromSub": null,
        "FeedbackRatingFromWorker": null
    }],
    availJobs: {
        "fromDb": false,
        "list": [{
            "Id": 555555,
            "TenantId": 555,
            "Start": "2015-11-27T08:45:00",
            "EndDate": "2015-11-27T00:00:00",
            "Items": [{
                "Id": 55555,
                "Start": "2015-11-27T08:45:00",
                "Duration": "07:30:00",
                "End": "2015-11-27T16:15:00",
                "ShiftType": 1,
                "NonPayTime": "00:00:00",
                "Institution": {
                    "Name": "White Marsh (Trappe) Elementary",
                    "Street1": "4322 Lovers Lane",
                    "Street2": "",
                    "Street3": null,
                    "Street4": null,
                    "City": "Trappe",
                    "State": "MD",
                    "Zip": "21673",
                    "Phone": "5555555555",
                    "ShowLocationPhoneToSub": true
                },
                "BreakDuration": "00:00:00",
                "VacancyId": 55555,
                "CanCancel": false
            }],
            "WorkerFirstName": "nosuchfirst",
            "WorkerLastName": "nosuchlst",
            "WorkerTitle": "2nd Grade",
            "WorkerReportLocation": null,
            "WorkerEmail": null,
            "WorkerIsVacancy": false,
            "ShowWorkerEmailAddrToSub": true,
            "HasNotes": true,
            "HasAttachments": false,
            "CanCancel": false,
            "SubWouldBePunishedForCancellingJob": false,
            "AwaitingFeedback": false,
            "CanViewFeedback": false,
            "CanViewFeedbackRating": false,
            "FeedbackRatingFromSub": null,
            "FeedbackRatingFromWorker": null
        }, {
            "Id": 5555555,
            "TenantId": 555,
            "Start": "2015-11-27T08:45:00",
            "EndDate": "2015-11-27T00:00:00",
            "Items": [{
                "Id": 555555,
                "Start": "2016-11-27T08:45:00",
                "Duration": "07:30:00",
                "End": "2015-11-27T16:15:00",
                "ShiftType": 1,
                "NonPayTime": "00:00:00",
                "Institution": {
                    "Name": "White Marsh (Trappe) Elementary",
                    "Street1": "4322 Lovers Lane",
                    "Street2": "",
                    "Street3": null,
                    "Street4": null,
                    "City": "Trappe",
                    "State": "MD",
                    "Zip": "21673",
                    "Phone": "5555555555",
                    "ShowLocationPhoneToSub": true
                },
                "BreakDuration": "00:00:00",
                "VacancyId": 555555,
                "CanCancel": false
            }],
            "WorkerFirstName": "nosuchfirst",
            "WorkerLastName": "nosuchlast",
            "WorkerTitle": "1st Grade",
            "WorkerReportLocation": null,
            "WorkerEmail": null,
            "WorkerIsVacancy": false,
            "ShowWorkerEmailAddrToSub": true,
            "HasNotes": true,
            "HasAttachments": false,
            "CanCancel": false,
            "SubWouldBePunishedForCancellingJob": false,
            "AwaitingFeedback": false,
            "CanViewFeedback": false,
            "CanViewFeedbackRating": false,
            "FeedbackRatingFromSub": null,
            "FeedbackRatingFromWorker": null
        }],
        "fromCache": false
    },
    nwds: [{
        "Ids": [5555555],
        "TenantIds": [5555],
        "TenantNames": ["Talbot County Schools"],
        "Created": "2015-11-07T06:05:37",
        "Start": "2015-11-07T00:00:00",
        "End": "2015-11-07T23:59:00",
        "Description": "Errands to run.",
        "IsPartOfGroup": false,
        "IsSystemGenerated": false,
        "AllDay": true
    }, {
        "Ids": [5555555],
        "TenantIds": [5555],
        "TenantNames": ["Talbot County Schools"],
        "Created": "2015-11-12T17:57:41",
        "Start": "2016-11-14T00:00:00",
        "End": "2016-11-14T23:59:00",
        "Description": "Chores and Errands",
        "IsPartOfGroup": false,
        "IsSystemGenerated": false,
        "AllDay": true
    }, {
        "Ids": [5555555555],
        "TenantIds": [55555],
        "TenantNames": ["Talbot County Schools"],
        "Created": "2016-11-19T21:47:06",
        "Start": "2013-11-20T00:00:00",
        "End": "2015-11-20T23:59:00",
        "Description": "school party volunteer",
        "IsPartOfGroup": false,
        "IsSystemGenerated": false,
        "AllDay": true
    }],
    tenants: {
        "11196": "Talbot County Schools"
    },
    startDate: new Date(2016, 9, 23, 0, 0, 0, 0),
    endDate: new Date(2013, 10, 22, 0, 0, 0, 0),
    historyDays: 30
				  """
//}

    /**
     * 
     * smaller full JSON
     */
      val availJobs = """{
   "availJobs": {
        "fromDb": false,
        "list": [{
            "Id": 55555555,
            "TenantId": 55555,
            "Start": "2014-11-27T08:45:00",
            "EndDate": "2015-11-27T00:00:00",
            "Items": [{
                "Id": 555555555,
                "Start": "2014-11-27T08:45:00",
                "Duration": "07:30:00",
                "End": "2014-11-27T16:15:00",
                "ShiftType": 1,
                "NonPayTime": "00:00:00",
                "Institution": {
                    "Name": "White Marsh (Trappe) Elementary",
                    "Street1": "4322 Lovers Lane",
                    "Street2": "",
                    "Street3": null,
                    "Street4": null,
                    "City": "Trappe",
                    "State": "MD",
                    "Zip": "21673",
                    "Phone": "5555555555",
                    "ShowLocationPhoneToSub": true
                },
                "BreakDuration": "00:00:00",
                "VacancyId": 555,
                "CanCancel": false
            }],
            "WorkerFirstName": "nosuchfirst",
            "WorkerLastName": "nosuchlast",
            "WorkerTitle": "2nd Grade",
            "WorkerReportLocation": null,
            "WorkerEmail": null,
            "WorkerIsVacancy": false,
            "ShowWorkerEmailAddrToSub": true,
            "HasNotes": true,
            "HasAttachments": false,
            "CanCancel": false,
            "SubWouldBePunishedForCancellingJob": false,
            "AwaitingFeedback": false,
            "CanViewFeedback": false,
            "CanViewFeedbackRating": false,
            "FeedbackRatingFromSub": null,
            "FeedbackRatingFromWorker": null
        }, {
            "Id": 95992765,
            "TenantId": 44444,
            "Start": "2016-11-27T08:45:00",
            "EndDate": "2016-11-27T00:00:00",
            "Items": [{
                "Id": 444444444,
                "Start": "2013-11-27T08:45:00",
                "Duration": "07:30:00",
                "End": "2014-11-27T16:15:00",
                "ShiftType": 1,
                "NonPayTime": "00:00:00",
                "Institution": {
                    "Name": "Elementary",
                    "Street1": "nosuchlane Lane",
                    "Street2": "",
                    "Street3": null,
                    "Street4": null,
                    "City": "Trappe",
                    "State": "MD",
                    "Zip": "22222",
                    "Phone": "5555555555",
                    "ShowLocationPhoneToSub": true
                },
                "BreakDuration": "00:00:00",
                "VacancyId": 95992765,
                "CanCancel": false
            }],
            "WorkerFirstName": "nosuchfirst",
            "WorkerLastName": "nosuchlast",
            "WorkerTitle": "1st Grade",
            "WorkerReportLocation": null,
            "WorkerEmail": null,
            "WorkerIsVacancy": false,
            "ShowWorkerEmailAddrToSub": true,
            "HasNotes": true,
            "HasAttachments": false,
            "CanCancel": false,
            "SubWouldBePunishedForCancellingJob": false,
            "AwaitingFeedback": false,
            "CanViewFeedback": false,
            "CanViewFeedbackRating": false,
            "FeedbackRatingFromSub": null,
            "FeedbackRatingFromWorker": null
        }],
        "fromCache": false
    }
}
	"""
        
 val sampleAesopInstitutionJson = """ { "Institution": {
                "Name": "Easton High School",
                "Street1": "723 Mecklenburg Avenue",
                "Street2": null,
                "Street3": null,
                "Street4": null,
                "City": "Easton",
                "State": "MD",
                "Zip": "21601",
                "Phone": "(410) 555-5555",
                "ShowLocationPhoneToSub": true
            } }"""
   
val sampleAesopInstitutionJson2 = """ {
            "Name": "Easton High School",
            "Street1": "723 Mecklenburg Avenue",
            "City": "Easton",
            "State": "MD",
            "Zip": "21601",
            "Phone": "(410) 555-5555",
            "ShowLocationPhoneToSub": true
        }"""

  val sampleAesopInstitutionJson3 = """ {
            "Name": "Easton High School",
            "Street1": "723 Mecklenburg Avenue",
            "City": "Easton",
            "Street2": null,
  			"Street3": null,
  			"Street4": null,
            "State": "MD",
            "Zip": "21601",
            "Phone": "(410) 555-5555",
            "ShowLocationPhoneToSub": true
        }"""

    
}